import {IFlight} from "../types/Flight.type";

export const FAKE_DATA: IFlight[] = [
    {
        API: "avia",
        AdultPrice: "41,583.00",
        Aircraft: "-",
        ArrivalDate: "Saturday, 06/05/2023",
        ArrivalTerminal: "",
        ArrivalTime: "14:30 +1",
        Baggage: "1 Piece 10 KG (Cabin)",
        Baggage_Details: [{title: "Adult", value: "30 KG"}, {title: "Child", value: "30 KG"}, {
            title: "Infant",
            value: "10 KG"
        }],
        BookId: "246696",
        CabinType: "E",
        ChildPrice: "0.00",
        Currency: "RUB",
        DepartureDate: "Friday, 05/05/2023",
        DepartureTerminal: "",
        DepartureTime: "23:40",
        Destination: "DXB",
        DestinationCity: "Dubai",
        Details: [
            {
                API: "avia",
                AdultPrice: "",
                Aircraft: "Boeing 737-800 with winglets",
                ArrivalDate: "Saturday, 06/05/2023",
                ArrivalTerminal: "C",
                ArrivalTime: "04:40",
                Baggage: "1 Piece 10 KG (Cabin)",
                Baggage_Details: null,
                BookId: "246696",
                CabinType: "E",
                ChildPrice: "",
                Currency: "RUB",
                DepartureDate: "Friday, 05/05/2023",
                DepartureTerminal: "",
                DepartureTime: "23:40",
                Destination: "SVO",
                DestinationCity: "Moscow",
                Details: [],
                Duration: "5H",
                FlightClass: "E",
                FlightNumber: "2135",
                Index: "0",
                InfantPrice: "",
                IsCharter: false,
                Logo: "/images/files/orange-all-logos/SU.png",
                Price: "41,583.00",
                ProviderId: "SU",
                ProviderName: "Aeroflot",
                Refundable: false,
                ResBookDesigCode: null,
                Rules: "",
                Seats: "1",
                Source: "IST",
                SourceCity: "Istanbul",
                Stops: 3,
                SupplierName: "Aeroflot",
                Tax: null,
                Tax_Details: null
            }, {
                API: "avia",
                AdultPrice: "",
                Aircraft: "Airbus A330-300",
                ArrivalDate: "Saturday, 06/05/2023",
                ArrivalTerminal: "1",
                ArrivalTime: "14:30",
                Baggage: "1 Piece 10 KG (Cabin)",
                Baggage_Details: null,
                BookId: "246727",
                CabinType: "E",
                ChildPrice: "",
                Currency: "RUB",
                DepartureDate: "Saturday, 06/05/2023",
                DepartureTerminal: "",
                DepartureTime: "07:50",
                Destination: "DXB",
                DestinationCity: "Dubai",
                Details: [],
                Duration: "5H & 40M",
                FlightClass: "E",
                FlightNumber: "520",
                Index: "1",
                InfantPrice: "",
                IsCharter: false,
                Logo: "/images/files/orange-all-logos/SU.png",
                Price: "43,633.00",
                ProviderId: "SU",
                ProviderName: "Aeroflot",
                Refundable: false,
                ResBookDesigCode: null,
                Rules: "",
                Seats: "1",
                Source: "SVO",
                SourceCity: "Moscow",
                Stops: 3,
                SupplierName: "Aeroflot",
                Tax: null,
                Tax_Details: null
            }
        ],
        Duration: "13H & 50M",
        FlightClass: "E",
        FlightNumber: "2135",
        Index: "0",
        InfantPrice: "0.00",
        IsCharter: false,
        Logo: "/images/files/orange-all-logos/SU.png",
        Price: "41,583.00",
        ProviderId: "SU",
        ProviderName: "Aeroflot",
        Refundable: false,
        ResBookDesigCode: null,
        Rules: "1)REFUND FEE: UNUSED CANCELLED TKT RUB 8,000 , UNUSED NO-SHOW TKT RUB 10,000 INBOUND TKT OF NO-SHOW PASSENGERS WILL BE CANCELLED AUTOMATICALLY WITHOUT NOTIFICATION;  2)CHANGE DATE PERMITTED AT CHARGE OF RUB 6,000 PER SEGMENT IN CASE OF AVAILABILITY IN SAME RBD BASED ON IRANIAN AIRLINES EXCHANGE RATE OTHERWISE THE DIFFERENCE OF RBD FARES AND TAX SHALL BE PAID BASED ON IRANIAN AIRLINES EXCHANGE RATE;  3)CHANGE DATE OF NO-SHOW TKT PERMITTED AT CHARGE OF RUB 10,000 PER NO-SHOW SEGMENT IN CASE OF AVAILABILITY IN SAME RBD BASED ON IRANIAN AIRLINES EXCHANGE RATE OTHERWISE THE DIFFERENCE OF RBD FARES AND TAX SHALL BE PAID BASED ON IRANIAN AIRLINES EXCHANGE RATE;  4)CONFIRM OPEN RETURN WITHIN TKT VALIDITY IN SAME RBD IS PERMITTED FREE OF CHARGE OTHERWISE THE DIFFERENCE OF RBD FARES AND TAX SHALL BE PAID BASED ON IRANIAN AIRLINES EXCHANGE RATE;  5)FREE BAG: 30KG, HAND BAG: 5KG, INF: 10KG (MAXIMUM OF TWO PIECES OF LUGGAGE ARE ALLOWED TO BE CHECKED IN PER TICKETED PASSENGER);  6)MAX STAY: 3 MONTHS; 7)PARTIALLY USED TKT DEDUCT ONE WAY FARE INSTEAD OF HALF ROUND TRIP FARE ; 8)EXCESS BAGGAGE: VKO/SVO/LED-IKA: RUB 1150 , IKA-VKO/SVO/LED:IRR 2,000,000 (9% VAT INCLUDED:IRR170,000); 9)OPEN JAW PERMITTED TO ALL W5 POINTS PROVIDED THE ROUND TRIP FARES OF ORIGIN ARE COMBINED ON1/2 RT BASIS.",
        Seats: "1",
        Source: "IST",
        SourceCity: "Istanbul",
        Stops: 3,
        SupplierName: "Aeroflot",
        Tax: null,
        Tax_Details: [
            {
                amount: 100,
                code: "YQ",
                currency: "RUB",
                pax_type: "Adult",
                title: "Red Cross Fee"
            },
            {
                amount: 299.5,
                code: "YQ",
                currency: "RUB",
                pax_type: "Child",
                title: "Airport Service Charge"
            }
        ]
    }
]
